# Generated by Django 3.2.4 on 2022-01-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(upload_to='profiles'),
        ),
    ]
